json_rpc_url: "http://127.0.0.1:8899"
websocket_url: "ws://127.0.0.1:8900/"
keypair_path: /home/kali/solana-fork/genesis-validator-key.json
address_labels:
  "11111111111111111111111111111111": System Program
commitment: confirmed
